/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAL.CustomerDAL;
import DAL.CustomerTypeDAL;
import DAL.MessageDialogDAL;
import DAL.ValidatorDAL;
import Enbity.Customer;
import Enbity.CustomerType;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author LongNguyen
 */
public class fCustomer extends javax.swing.JFrame {

    private DefaultTableModel model;
    private DefaultComboBoxModel<CustomerType> modelcb;
    private DefaultTreeModel modeltree;

    /**
     * Creates new form Customer
     */
    public fCustomer() {
        this.setLocationRelativeTo(null);
        initComponents();
        initTable();
        initComBoBox();
        FillDatacComBoBoxGUI();
        try {
            FillDataTableGUI();
        } catch (SQLException ex) {
            MessageDialogDAL.showErrorrDialog(this, ex.getMessage(), "Errorr");
        }
        initTree();
        initIcon();
    }
    
    private void initIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    private void initTree() {
        try {
            DefaultMutableTreeNode rootnote = new DefaultMutableTreeNode("Customer group");

            CustomerTypeDAL dal = new CustomerTypeDAL();
            List<CustomerType> list = dal.FillDataCustomerTypes();

            for (var i : list) {
                DefaultMutableTreeNode chilnote = new DefaultMutableTreeNode(i);
                rootnote.add(chilnote);
            }
            modeltree = new DefaultTreeModel(rootnote);
            treetype.setModel(modeltree);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void initTable() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "Customer ID", "Full Name", "Number Phone", "Gmail"
        });
        tblCustomer.setModel(model);
    }

    private void initComBoBox() {
        modelcb = new DefaultComboBoxModel<>();
        cbtype.setModel(modelcb);
    }

    private void FillDatacComBoBoxGUI() {
        try {
            CustomerTypeDAL dl = new CustomerTypeDAL();
            List<CustomerType> list = dl.FillDataCustomerTypes();
            for (CustomerType i : list) {
                modelcb.addElement(i);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void FillDataTableGUI() throws SQLException {
        CustomerDAL cs = new CustomerDAL();
        List<Customer> list = cs.FillDataTable();
        model.setRowCount(0);
        for (Customer i : list) {
            model.addRow(new Object[]{
                i.getId(), i.getName(), i.getPhone(), i.getEmail()
            });
        }

        model.fireTableDataChanged();
    }

    private void resetvalues() {
        cbtype.setSelectedIndex(-1);
        txtid.setText("");
        txtname.setText("");
        txtphone.setText("");
        txtgmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treetype = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbtype = new javax.swing.JComboBox<>();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtgmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupd = new javax.swing.JButton();
        btndel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cusstomer manage");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        treetype.setFont(new java.awt.Font("Dialog", 3, 13)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treetype.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treetype.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treetypeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treetype);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCustomer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\typecustomer.png")); // NOI18N
        jLabel1.setText("Customer Type ");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\name.png")); // NOI18N
        jLabel2.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\phone.png")); // NOI18N
        jLabel3.setText("Number Phone");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\gmail.png")); // NOI18N
        jLabel4.setText("Gmail");

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\ID.png")); // NOI18N
        jLabel5.setText("Customer ID");

        cbtype.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        txtid.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtid.setEnabled(false);
        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidMouseClicked(evt);
            }
        });

        txtname.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameMouseClicked(evt);
            }
        });

        txtphone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtphoneMouseClicked(evt);
            }
        });

        txtgmail.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtgmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtgmailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbtype, 0, 225, Short.MAX_VALUE)
                    .addComponent(txtid)
                    .addComponent(txtname)
                    .addComponent(txtphone)
                    .addComponent(txtgmail))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        btnadd.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\add.png")); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel5.add(btnadd);

        btnsave.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\save.png")); // NOI18N
        btnsave.setText("Save");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnsave);

        btnupd.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        btnupd.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\update.png")); // NOI18N
        btnupd.setText("Update");
        btnupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdActionPerformed(evt);
            }
        });
        jPanel5.add(btnupd);

        btndel.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        btndel.setIcon(new javax.swing.ImageIcon("C:\\Users\\longl\\OneDrive\\Documents\\NetBeansProjects\\CustomerManageer\\image\\delete.png")); // NOI18N
        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        jPanel5.add(btndel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        btnsave.setEnabled(true);
        txtid.setEnabled(true);
        resetvalues();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdActionPerformed
        StringBuilder sbd = new StringBuilder();
        ValidatorDAL.ValidateEnbity(cbtype, sbd, "Please choose the type of customer !");
        ValidatorDAL.ValidateEnbity(txtid, sbd, "Please enter your Customer ID !");
        ValidatorDAL.ValidateEnbity(txtname, sbd, "Please enter your Fullname !");
        ValidatorDAL.ValidateEnbity(txtphone, sbd, "Please enter your Number Phone !");

        if (sbd.length() > 0) {
            MessageDialogDAL.showErrorrDialog(this, sbd.toString(), "Errorr");
            return;
        }
        try {
            Customer cs = new Customer();
            cs.setId(txtid.getText());
            cs.setTypeid(((CustomerType) cbtype.getSelectedItem()).getTypeid());
            cs.setName(txtname.getText());
            cs.setPhone(txtphone.getText());
            cs.setEmail(txtgmail.getText());

            CustomerDAL cdl = new CustomerDAL();

            if (cdl.UpdateCustomer(cs)) {
                FillDataTableGUI();
                MessageDialogDAL.showMrssageDialog(this, "Update Success", "Notification");
                resetvalues();
            } else {
                MessageDialogDAL.showErrorrDialog(this, "Update Errorr", "Errorr");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogDAL.showErrorrDialog(this, e.getMessage(), "Errorr");
        }
    }//GEN-LAST:event_btnupdActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        StringBuilder sbd = new StringBuilder();
        ValidatorDAL.ValidateEnbity(txtid, sbd, "Please enter your Customer ID !");

        if (sbd.length() > 0) {
            MessageDialogDAL.showErrorrDialog(this, sbd.toString(), "Errorr");
            return;
        }

        try {
            if (MessageDialogDAL.showConfirmDialog(this, "Are you sure you want to delete", "Question")
                    == JOptionPane.YES_OPTION) {
                CustomerDAL csdal = new CustomerDAL();
                if (csdal.DeleteCustomer(txtid.getText().toString())) {
                    FillDataTableGUI();
                    resetvalues();
                    MessageDialogDAL.showMrssageDialog(this, "Delete Success", "Notification");
                } else {
                    MessageDialogDAL.showErrorrDialog(this, "Delete Errorr", "Errorr");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogDAL.showErrorrDialog(this, e.getMessage(), "Errorr");
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        StringBuilder sbd = new StringBuilder();

        ValidatorDAL.ValidateEnbity(cbtype, sbd, "Please choose the type of customer !");
        ValidatorDAL.ValidateEnbity(txtid, sbd, "Please enter your Customer ID !");
        ValidatorDAL.ValidateEnbity(txtname, sbd, "Please enter your Fullname !");
        ValidatorDAL.ValidateEnbity(txtphone, sbd, "Please enter your Number Phone !");

        if (sbd.length() > 0) {
            MessageDialogDAL.showErrorrDialog(this, sbd.toString(), "Errorr");
            return;
        }
        try {
            Customer cs = new Customer();
            cs.setId(txtid.getText());
            cs.setTypeid(((CustomerType) cbtype.getSelectedItem()).getTypeid());
            cs.setName(txtname.getText());
            cs.setPhone(txtphone.getText());
            cs.setEmail(txtgmail.getText());

            CustomerDAL csdal = new CustomerDAL();
            if (csdal.AddCustomer(cs) == true) {
                FillDataTableGUI();
                btnsave.setEnabled(false);
                txtid.setEnabled(false);
                resetvalues();
                MessageDialogDAL.showMrssageDialog(this, "Add Success", "Notification");
            } else {
                MessageDialogDAL.showErrorrDialog(this, "Add Errorr", "Errorr");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogDAL.showErrorrDialog(this, e.getMessage(), "Errorr");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        try {
            int rows = tblCustomer.getSelectedRow();

            if (rows >= 0) {
                String id = (String) tblCustomer.getValueAt(rows, 0);

                CustomerDAL csdal = new CustomerDAL();
                Customer cs = csdal.FindCustomer(id);

                if (cs != null) {
                    CustomerTypeDAL csDAL = new CustomerTypeDAL();
                    List<CustomerType> list = csDAL.FillDataCustomerTypes();
                    int index = 0;
                    for(var i : list){
                        if(i.getTypeid().equals(cs.getTypeid())){
                        cbtype.setSelectedIndex(index);
                        break;
                        }
                        index++;
                    }
                    txtid.setText(cs.getId());
                    txtname.setText(cs.getName());
                    txtphone.setText(cs.getPhone());
                    txtgmail.setText(cs.getEmail());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void txtidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidMouseClicked
        txtid.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtidMouseClicked

    private void txtnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMouseClicked
        txtname.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtnameMouseClicked

    private void txtphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtphoneMouseClicked
        txtphone.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtphoneMouseClicked

    private void txtgmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtgmailMouseClicked
        txtgmail.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtgmailMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fLogin lg = new fLogin();
        lg.show();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void treetypeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treetypeValueChanged
        if(treetype.isSelectionEmpty()){
            return;
        }
        TreePath path = treetype.getSelectionPath();
        DefaultMutableTreeNode selectnote = (DefaultMutableTreeNode) path.getLastPathComponent();
        Object obj = selectnote.getUserObject();
        CustomerType cs = (CustomerType) obj;
        try {
           CustomerDAL csdal = new CustomerDAL();
           List<Customer> list = csdal.FillDataTableByID(cs.getTypeid());
        model.setRowCount(0);
        for (Customer i : list) {
            model.addRow(new Object[]{
                i.getId(), i.getName(), i.getPhone(), i.getEmail()
            });
        }
        model.fireTableDataChanged();
        } catch (Exception e) {
            MessageDialogDAL.showErrorrDialog(this, e.getMessage(), "Errorr");
        }
    }//GEN-LAST:event_treetypeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupd;
    private javax.swing.JComboBox<CustomerType> cbtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTree treetype;
    private javax.swing.JTextField txtgmail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
